version: '3.1'

services:
  mysql:
    image: mysql:latest # use latest official postgres version
    container_name: MySQL
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
     MYSQL_USER: rainbow
     MYSQL_PASSWORD: password
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: rainbow
     MYSQL_ALLOW_EMPTY_PASSWORD: 1  #Лишнее, дебажить, убрать
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

  postgressql:
    image: postgres:latest # use latest official postgres version
    container_name: PostgreSQL
    restart: unless-stopped
    ports:
      - "5432:3307"
    environment:
            POSTGRES_USER: unicorn
            POSTGRES_DB: unicorn
            POSTGRES_HOST_AUTH_METHOD: trust #Лишнее, дебажить, убрать
    volumes: 
      - postgresql_data:/var/lib/postgresql/
    networks:
      - app

#Docker Networks
networks:
    app:
        driver: bridge

volumes:
    mysql_data:
    postgresql_data:
